// src/modules/resumes/parsing/resume.parser.js

import {
  createEmptyResume,
  createEducation,
  createExperience,
  createProject,
  createCertification,
  createLanguage,
  createReference,
} from "./resume.schema.js";

// ======================================================
// SECTION ALIASES
// ======================================================

const SECTION_ALIASES = {
  summary: [
    "summary",
    "professional summary",
    "profile",
    "professional profile",
    "professional profile summary",
    "objective",
    "career objective",
    "career objectives",
    "about me",
    "about",
    "personal statement",
    "overview",
  ],

  experience: [
    "experience",
    "work experience",
    "professional experience",
    "employment history",
    "work history",
    "career history",
    "employment",
    "work",
    "professional background",
  ],

  education: [
    "education",
    "education qualification",
    "education qualifications",
    "academic background",
    "academic qualification",
    "academic qualifications",
    "educational qualification",
    "educational qualifications",
    "qualifications",
    "academic history",
    "academic qualifications",
  ],

  skills: [
    "skills",
    "skill",
    "technical skills",
    "technical skill",
    "core skills",
    "key skills",
    "competencies",
    "technical competencies",
    "area of expertise",
    "areas of expertise",
    "expertise",
    "technologies",
    "technical proficiency",
  ],

  projects: [
    "projects",
    "project",
    "personal projects",
    "academic projects",
    "key projects",
    "selected projects",
  ],

  certifications: [
    "certifications",
    "certification",
    "certificates",
    "certificate",
    "licenses",
    "licenses & certifications",
    "licenses and certifications",
  ],

  languages: [
    "languages",
    "language",
    "language proficiency",
    "language skills",
    "languages skills",
  ],

  achievements: [
    "achievements",
    "achievement",
    "awards",
    "award",
    "honors",
    "honours",
    "accomplishments",
  ],

  references: ["references", "reference", "reference(s)", "reference (s)"],

  // Important:
  // We detect "Others" so that it doesn't get swallowed
  // by the Languages parser.
  otherSkills: [
    "others",
    "other",
    "other skills",
    "soft skills",
    "professional skills",
  ],
};

// ======================================================
// CONSTANTS
// ======================================================

const GARBAGE_PATTERNS = [
  /^--\s*\d+\s*of\s*\d+\s*--$/i,
  /^page\s+\d+(\s+of\s+\d+)?$/i,
  /^\d+\s*\/\s*\d+$/,
  /^powered by/i,
  /^generated by/i,
];

const MONTH_PATTERN =
  "(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)";

// ======================================================
// MAIN PARSER
// ======================================================

export const parseResume = async (rawText) => {
  const resume = createEmptyResume();

  const text = normalizeRawText(rawText);

  if (!text) {
    return resume;
  }

  const lines = text
    .split("\n")
    .map(cleanLine)
    .filter(Boolean)
    .filter((line) => !isGarbageLine(line));

  // ----------------------------------------------------
  // Personal
  // ----------------------------------------------------

  parsePersonalInformation(text, lines, resume);

  // ----------------------------------------------------
  // Links
  // ----------------------------------------------------

  const links = extractLinks(text);

  resume.socialLinks.linkedin = links.linkedin;
  resume.socialLinks.github = links.github;
  resume.socialLinks.other = links.other;
  resume.portfolio = links.portfolio;

  // ----------------------------------------------------
  // Sections
  // ----------------------------------------------------

  const sections = detectSections(lines);

  // ----------------------------------------------------
  // Summary
  // ----------------------------------------------------

  resume.summary = parseSummary(sections.summary || []);

  // ----------------------------------------------------
  // Skills
  // ----------------------------------------------------

  resume.skills = parseSkills(sections.skills || []);

  // Include soft/other skills as skills only when useful.
  const otherSkills = parseOtherSkills(sections.otherSkills || []);

  resume.skills = unique([...(resume.skills || []), ...otherSkills]);

  // ----------------------------------------------------
  // Education
  // ----------------------------------------------------

  resume.education = parseEducation(sections.education || []);

  // ----------------------------------------------------
  // Experience
  // ----------------------------------------------------

  resume.experience = parseExperience(sections.experience || []);

  // ----------------------------------------------------
  // Projects
  // ----------------------------------------------------

  resume.projects = parseProjects(sections.projects || []);

  // ----------------------------------------------------
  // Certifications
  // ----------------------------------------------------

  resume.certifications = parseCertifications(sections.certifications || []);

  // ----------------------------------------------------
  // Languages
  // ----------------------------------------------------

  resume.languages = parseLanguages(sections.languages || []);

  // ----------------------------------------------------
  // Achievements
  // ----------------------------------------------------

  resume.achievements = parseSimpleList(sections.achievements || []);

  // ----------------------------------------------------
  // References
  // ----------------------------------------------------

  resume.references = parseReferences(sections.references || []);

  return cleanupResume(resume);
};

// ======================================================
// NORMALIZATION
// ======================================================

const normalizeRawText = (text) => {
  return String(text || "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/\u00a0/g, " ")
    .replace(/[ \t]+/g, " ")
    .replace(/\n[ \t]+/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
};

const cleanLine = (line) => {
  return String(line || "")
    .replace(/\u00a0/g, " ")
    .replace(/[ \t]+/g, " ")
    .replace(/\s+([,:;])/g, "$1")
    .trim();
};

const isGarbageLine = (line) => {
  const cleaned = cleanLine(line);

  if (!cleaned) {
    return true;
  }

  return GARBAGE_PATTERNS.some((pattern) => pattern.test(cleaned));
};

// ======================================================
// PERSONAL INFORMATION
// ======================================================

const parsePersonalInformation = (text, lines, resume) => {
  resume.personal.name = extractName(lines);

  const headerText = getHeaderText(lines);

  resume.personal.email = extractPrimaryEmail(headerText);

  resume.personal.alternateEmail = extractAlternateEmail(headerText);

  resume.personal.phone = extractPrimaryPhone(headerText);

  resume.personal.alternatePhone = extractAlternatePhone(headerText);

  resume.personal.location = extractLocation(lines);

  resume.personal.dateOfBirth = extractLabelValue(text, [
    "date of birth",
    "dob",
    "birth date",
    "birthdate",
  ]);

  resume.personal.gender = extractLabelValue(text, ["gender", "sex"]);

  resume.personal.nationality = extractLabelValue(text, [
    "nationality",
    "citizenship",
  ]);

  resume.personal.maritalStatus = extractLabelValue(text, [
    "marital status",
    "marital",
  ]);

  resume.personal.bloodGroup = extractLabelValue(text, [
    "blood group",
    "blood type",
  ]);

  resume.personal.fatherName = extractLabelValue(text, [
    "father's name",
    "father name",
    "father",
  ]);

  resume.personal.motherName = extractLabelValue(text, [
    "mother's name",
    "mother name",
    "mother",
  ]);

  resume.personal.religion = extractLabelValue(text, ["religion"]);

  resume.personal.height = extractLabelValue(text, [
    "height",
    "height (meter)",
    "height (m)",
  ]);

  resume.personal.weight = extractLabelValue(text, [
    "weight",
    "weight (kg)",
    "weight (kilogram)",
  ]);
};

// Only inspect the header.
// This prevents reference phone numbers from becoming
// alternate candidate phone numbers.
const getHeaderText = (lines) => {
  const sectionStart = lines.findIndex((line) => detectSectionHeading(line));

  const headerLines =
    sectionStart === -1 ? lines.slice(0, 30) : lines.slice(0, sectionStart);

  return headerLines.join("\n");
};

// ======================================================
// NAME
// ======================================================

const extractName = (lines) => {
  const firstLines = lines.slice(0, 15);

  for (const line of firstLines) {
    const cleaned = cleanLine(line);

    if (!cleaned) continue;

    if (isGarbageLine(cleaned) || /powered by/i.test(cleaned)) {
      continue;
    }

    if (
      /^(address|current address|location|primary mobile|mobile|phone|telephone|email|primary email|alternate email|linkedin|github|website|portfolio)\s*[:\-]?/i.test(
        cleaned,
      )
    ) {
      continue;
    }

    if (
      cleaned.includes("@") ||
      /^https?:\/\//i.test(cleaned) ||
      /\d{5,}/.test(cleaned)
    ) {
      continue;
    }

    if (isSectionHeading(cleaned)) {
      continue;
    }

    if (
      cleaned.length >= 3 &&
      cleaned.length <= 80 &&
      /^[A-Za-zÀ-ÿ.' -]+$/.test(cleaned)
    ) {
      return cleaned;
    }
  }

  return "";
};

// ======================================================
// EMAIL
// ======================================================

const extractEmails = (text) => {
  const matches =
    text.match(/[A-Z0-9._%+-]+\s*@\s*[A-Z0-9.-]+\s*\.[A-Z]{2,}/gi) || [];

  return unique(
    matches.map((email) => email.replace(/\s+/g, "").toLowerCase()),
  );
};

const extractPrimaryEmail = (text) => {
  return extractEmails(text)[0] || "";
};

const extractAlternateEmail = (text) => {
  return extractEmails(text)[1] || "";
};

// ======================================================
// PHONE
// ======================================================

const extractPhones = (text) => {
  const matches =
    text.match(
      /(?:\+?88[\s-]?)?01[3-9][\s-]?\d{3}[\s-]?\d{3}[\s-]?\d{2}|\+?\d[\d\s().-]{7,}\d/g,
    ) || [];

  const normalized = matches
    .map((phone) => phone.replace(/[^\d+]/g, "").trim())
    .filter((phone) => {
      const digits = phone.replace(/\D/g, "");

      return digits.length >= 10 && digits.length <= 15;
    });

  return unique(normalized);
};

const extractPrimaryPhone = (text) => {
  return extractPhones(text)[0] || "";
};

const extractAlternatePhone = (text) => {
  return extractPhones(text)[1] || "";
};

// ======================================================
// LABEL VALUE
// ======================================================

const extractLabelValue = (text, labels) => {
  const lines = text.split("\n");

  for (const line of lines) {
    const cleaned = cleanLine(line);

    for (const label of labels) {
      const escaped = escapeRegex(label);

      const inlineRegex = new RegExp(`^${escaped}\\s*[:\\-]?\\s*(.+)$`, "i");

      const match = cleaned.match(inlineRegex);

      if (match?.[1]) {
        const value = cleanLine(match[1]);

        if (value && !isSectionHeading(value)) {
          return value;
        }
      }
    }
  }

  return "";
};

// ======================================================
// LOCATION
// ======================================================

const extractLocation = (lines) => {
  const labels = [
    "current location",
    "current address",
    "present address",
    "permanent address",
    "address",
    "location",
  ];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    for (const label of labels) {
      const regex = new RegExp(
        `^${escapeRegex(label)}\\s*[:\\-]?\\s*(.*)$`,
        "i",
      );

      const match = line.match(regex);

      if (!match) continue;

      let value = cleanLine(match[1]);

      // Address continuation
      if (
        i + 1 < lines.length &&
        !isSectionHeading(lines[i + 1]) &&
        !looksLikeContactLine(lines[i + 1])
      ) {
        const next = lines[i + 1];

        if (looksLikeAddressContinuation(next)) {
          value = value ? `${value}, ${next}` : next;
        }
      }

      if (value) {
        return normalizeAddress(value);
      }
    }
  }

  // Search top area for location.
  const locationKeywords = [
    "dhaka",
    "uttara",
    "mirpur",
    "gulshan",
    "banani",
    "dhanmondi",
    "bashundhara",
    "cumilla",
    "comilla",
    "chattogram",
    "chittagong",
    "sylhet",
    "rajshahi",
    "khulna",
    "barisal",
    "bangladesh",
    "india",
    "usa",
    "canada",
    "united states",
  ];

  for (const line of lines.slice(0, 20)) {
    const lower = line.toLowerCase();

    if (locationKeywords.some((keyword) => lower.includes(keyword))) {
      if (!looksLikeContactLine(line)) {
        return normalizeAddress(line);
      }
    }
  }

  return "";
};

const normalizeAddress = (value) => {
  return cleanLine(value)
    .replace(/\s*,\s*,+/g, ",")
    .replace(/\s*-\s*/g, " - ")
    .trim();
};

const looksLikeAddressContinuation = (line) => {
  return (
    /\d/.test(line) ||
    /road|rd|street|st|avenue|ave|sector|block|house|flat|floor|dhaka|bangladesh/i.test(
      line,
    )
  );
};

const looksLikeContactLine = (line) => {
  return (
    /@/.test(line) ||
    /https?:\/\//i.test(line) ||
    /(?:mobile|phone|telephone|email|linkedin|github)\s*:/i.test(line)
  );
};

// ======================================================
// LINKS
// ======================================================

const extractLinks = (text) => {
  const urls = text.match(/https?:\/\/[^\s<>)]+/gi) || [];

  let linkedin = "";
  let github = "";
  let portfolio = "";

  const other = [];

  for (const rawUrl of urls) {
    const url = rawUrl.replace(/[),.;]+$/, "");

    const lower = url.toLowerCase();

    if (lower.includes("linkedin.com")) {
      linkedin = url;
    } else if (lower.includes("github.com")) {
      github = url;
    } else if (
      lower.includes("portfolio") ||
      lower.includes("vercel.app") ||
      lower.includes("netlify.app") ||
      lower.includes("gitlab.io")
    ) {
      portfolio = url;
    } else {
      other.push(url);
    }
  }

  return {
    linkedin,
    github,
    portfolio,
    other: unique(other),
  };
};

// ======================================================
// SECTION DETECTION
// ======================================================

const detectSections = (lines) => {
  const sections = {
    header: [],
  };

  let current = "header";

  for (const line of lines) {
    const section = detectSectionHeading(line);

    if (section) {
      current = section;

      if (!sections[current]) {
        sections[current] = [];
      }

      continue;
    }

    if (!sections[current]) {
      sections[current] = [];
    }

    sections[current].push(line);
  }

  return sections;
};

const detectSectionHeading = (line) => {
  const cleaned = normalizeHeading(line);

  if (!cleaned) {
    return null;
  }

  for (const [section, aliases] of Object.entries(SECTION_ALIASES)) {
    for (const alias of aliases) {
      if (cleaned === normalizeHeading(alias)) {
        return section;
      }
    }
  }

  if (/^career objectives?$/.test(cleaned)) {
    return "summary";
  }

  if (/^academic qualifications?$/.test(cleaned)) {
    return "education";
  }

  if (/^technical skills?$/.test(cleaned)) {
    return "skills";
  }

  if (/^language skills?$/.test(cleaned)) {
    return "languages";
  }

  return null;
};

const normalizeHeading = (line) => {
  return cleanLine(line)
    .toLowerCase()
    .replace(/[:|]/g, "")
    .replace(/[._]+$/g, "")
    .replace(/\s+/g, " ")
    .trim();
};

const isSectionHeading = (line) => {
  return Boolean(detectSectionHeading(line));
};

// ======================================================
// SUMMARY
// ======================================================

const parseSummary = (lines) => {
  return lines
    .filter((line) => !isGarbageLine(line))
    .map(removeBullet)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
};

// ======================================================
// SKILLS
// ======================================================

const parseSkills = (lines) => {
  const skills = [];

  for (const rawLine of lines) {
    let line = removeBullet(rawLine);

    if (!line) continue;

    if (
      /^(technical skills?|soft skills?|other skills?|professional skills?|language skills?)\s*:?\s*$/i.test(
        line,
      )
    ) {
      continue;
    }

    const parts = line.split(/[,;|•·]+/);

    for (const item of parts) {
      const skill = cleanLine(item);

      // Allow one-character skills such as C.
      if (!skill || skill.length < 1 || skill.length > 100) {
        continue;
      }

      if (looksLikeSkillSentence(skill)) {
        continue;
      }

      skills.push(normalizeSkill(skill));
    }
  }

  return unique(skills);
};

const parseOtherSkills = (lines) => {
  const result = [];

  for (const rawLine of lines) {
    const line = removeBullet(rawLine);

    if (!line) continue;

    // Don't add prose as a technical skill.
    // Keep these as achievements/soft skills only
    // if they are useful.
    if (
      line.length <= 100 &&
      !/^(others?|other skills?|soft skills?)\s*:?\s*$/i.test(line)
    ) {
      result.push(line);
    }
  }

  return result;
};

const normalizeSkill = (skill) => {
  return skill.replace(/^skills?\s*:\s*/i, "").trim();
};

const looksLikeSkillSentence = (line) => {
  if (line.length > 70) {
    return true;
  }

  return /^(strong|ability|experienced|responsible|worked|working|excellent|good|proven|capable|flexible|well-built)\b/i.test(
    line,
  );
};

// ======================================================
// EDUCATION
// ======================================================

const parseEducation = (lines) => {
  const entries = [];

  let current = null;

  const pushCurrent = () => {
    if (!current) return;

    current = finalizeEducation(current);

    if (
      current.degree ||
      current.institution ||
      current.result ||
      current.department
    ) {
      entries.push(current);
    }

    current = null;
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = cleanLine(lines[i]);

    if (!rawLine) continue;

    if (isEducationTableHeader(rawLine)) {
      continue;
    }

    const labeled = parseEducationLabel(rawLine);

    if (labeled) {
      if (!current) {
        current = createEducation();
      }

      if (labeled.type === "institution") {
        current.institution = labeled.value;

        // Consume wrapped institution line.
        const next = lines[i + 1];

        if (
          next &&
          !isEducationMetadataLine(next) &&
          !isSectionHeading(next) &&
          looksLikeInstitutionContinuation(next)
        ) {
          current.institution = `${current.institution} ${cleanLine(next)}`;

          i++;
        }
      }

      if (labeled.type === "degree") {
        current.degree = labeled.value;
      }

      if (labeled.type === "department") {
        current.department = labeled.value;
      }

      if (labeled.type === "result") {
        current.result = labeled.result;

        current.resultScale = labeled.scale;
      }

      continue;
    }

    const year = extractYearRange(rawLine);

    const result = extractResult(rawLine);

    const degree = isDegreeLine(rawLine);

    const institution = isInstitutionLine(rawLine);

    const department = extractDepartment(rawLine);

    if (
      degree &&
      current &&
      current.degree &&
      (institution || year || result)
    ) {
      pushCurrent();
    }

    if (degree || institution || year || result || department) {
      if (!current) {
        current = createEducation();
      }

      if (degree && !current.degree && !isEducationNoise(rawLine)) {
        current.degree = cleanDegree(rawLine);
      }

      if (institution && !current.institution) {
        current.institution = cleanInstitution(rawLine);

        const next = lines[i + 1];

        if (
          next &&
          !isEducationMetadataLine(next) &&
          looksLikeInstitutionContinuation(next)
        ) {
          current.institution = `${current.institution} ${cleanLine(next)}`;

          i++;
        }
      }

      if (department) {
        current.department = department;
      }

      if (result) {
        current.result = result.value;

        current.resultScale = result.scale;
      }

      if (year) {
        current.startYear = year.start;

        current.endYear = year.end;
      }

      if (/\b(running|present|current)\b/i.test(rawLine) && !current.endYear) {
        current.endYear = "Present";
      }

      const useful = removeEducationMetadata(rawLine);

      if (
        useful &&
        !degree &&
        !institution &&
        !result &&
        !year &&
        !department
      ) {
        appendDescription(current, useful);
      }

      continue;
    }

    if (current) {
      if (isEducationNoise(rawLine)) {
        continue;
      }

      appendDescription(current, rawLine);
    }
  }

  pushCurrent();

  return entries;
};

// ======================================================
// EDUCATION HELPERS
// ======================================================

const parseEducationLabel = (line) => {
  const labels = [
    {
      type: "institution",
      labels: ["institution", "university", "college", "school", "institute"],
    },
    {
      type: "degree",
      labels: ["degree", "qualification"],
    },
    {
      type: "department",
      labels: [
        "department",
        "major",
        "field",
        "concentration",
        "specialization",
        "specialisation",
      ],
    },
  ];

  for (const item of labels) {
    for (const label of item.labels) {
      const regex = new RegExp(`^${escapeRegex(label)}\\s*:\\s*(.+)$`, "i");

      const match = line.match(regex);

      if (match?.[1]) {
        return {
          type: item.type,
          value: cleanLine(match[1]),
        };
      }
    }
  }

  const result = extractResult(line);

  if (result) {
    return {
      type: "result",
      result: result.value,
      scale: result.scale,
    };
  }

  return null;
};

const isEducationTableHeader = (line) => {
  return /^(degree|degree details|details|result|year|qualification)\s*(details\s*)?(result\s*)?(year)?$/i.test(
    line,
  );
};

const isEducationMetadataLine = (line) => {
  return (
    isEducationTableHeader(line) ||
    /^(institution|degree|qualification|department|major|field|concentration|specialization|specialisation|result|cgpa|gpa|grade|year)\s*:/i.test(
      line,
    ) ||
    extractResult(line) ||
    extractYearRange(line)
  );
};

const looksLikeInstitutionContinuation = (line) => {
  const cleaned = cleanLine(line);

  if (!cleaned) return false;

  if (isSectionHeading(cleaned) || isEducationMetadataLine(cleaned)) {
    return false;
  }

  return /^[A-Za-zÀ-ÿ0-9&.,'’–— -]+$/.test(cleaned) && cleaned.length <= 120;
};

const isEducationNoise = (line) => {
  return (
    /^(degree details result year|degree details|details|result|year)$/i.test(
      line,
    ) || /^institution\s*:?\s*$/i.test(line)
  );
};

const cleanDegree = (line) => {
  return cleanLine(
    line.replace(/^degree\s*:\s*/i, "").replace(/^qualification\s*:\s*/i, ""),
  );
};

const cleanInstitution = (line) => {
  return cleanLine(
    line.replace(
      /^(institution|university|college|school|institute)\s*:\s*/i,
      "",
    ),
  );
};

const removeEducationMetadata = (line) => {
  return cleanLine(
    line.replace(
      /^(institution|degree|qualification|department|major|field|concentration|specialization|specialisation|result|cgpa|gpa|grade|year)\s*:\s*/i,
      "",
    ),
  );
};

const finalizeEducation = (education) => {
  education.degree = cleanLine(education.degree || "");

  education.institution = cleanLine(education.institution || "");

  education.department = cleanLine(education.department || "");

  education.result = cleanLine(education.result || "");

  education.description = cleanLine(education.description || "");

  return education;
};

const isDegreeLine = (line) => {
  return /(bachelor|bachelors|master|masters|phd|doctor|b\.?\s?sc|m\.?\s?sc|b\.?\s?s|m\.?\s?s|bba|mba|b\.?\s?e|beng|meng|be|diploma|degree|hsc|ssc|higher secondary|secondary school|associate)/i.test(
    line,
  );
};

const isInstitutionLine = (line) => {
  return /(university|college|institute|school|academy|polytechnic)/i.test(
    line,
  );
};

const extractDepartment = (line) => {
  const match = line.match(
    /(?:major|concentration|department|field|specialization|specialisation)\s*[:\-]?\s*(.+)/i,
  );

  return match ? cleanLine(match[1]) : "";
};

// Supports:
//
// CGPA: 3.18 / 4.00
// GPA: 3.18 out of 4.00
// Result: 3.18 out of 4.00
// 3.18 out of 4.00
// 3.18/4.00
const extractResult = (line) => {
  const cleaned = cleanLine(line);

  const match = cleaned.match(
    /(?:\b(?:cgpa|gpa|grade|result)\b\s*[:\-]?\s*)?([0-9]+(?:\.[0-9]+)?)\s*(?:out\s+of|\/)\s*([0-9]+(?:\.[0-9]+)?)/i,
  );

  if (match) {
    return {
      value: match[1],
      scale: `out of ${match[2]}`,
    };
  }

  const labeled = cleaned.match(
    /\b(?:cgpa|gpa|grade|result)\s*[:\-]?\s*([0-9]+(?:\.[0-9]+)?)/i,
  );

  if (labeled) {
    return {
      value: labeled[1],
      scale: "",
    };
  }

  return null;
};

// ======================================================
// EXPERIENCE
// ======================================================

const parseExperience = (lines) => {
  const entries = [];

  let current = null;

  const pushCurrent = () => {
    if (!current) return;

    current.title = cleanLine(current.title);

    current.company = cleanLine(current.company);

    current.description = cleanLine(current.description);

    if (current.title || current.company || current.description) {
      entries.push(current);
    }

    current = null;
  };

  for (const rawLine of lines) {
    const line = cleanLine(rawLine);

    if (!line) continue;

    const date = extractDateRange(line);

    const role = isJobTitle(line);

    const company = isCompanyLine(line);

    if (role && !isBullet(line)) {
      if (current?.title) {
        pushCurrent();
      }

      current = createExperience();

      current.title = removeDuration(line);

      if (date) {
        current.startDate = date.start;

        current.endDate = date.end;
      }

      continue;
    }

    if (!current) {
      current = createExperience();
    }

    if (date && !current.startDate) {
      current.startDate = date.start;

      current.endDate = date.end;

      continue;
    }

    if (company && !current.company) {
      current.company = line;
      continue;
    }

    if (isBullet(line)) {
      appendExperienceDescription(current, removeBullet(line));

      continue;
    }

    if (current.title && !current.company && !isGenericExperienceText(line)) {
      current.company = line;
      continue;
    }

    appendExperienceDescription(current, line);
  }

  pushCurrent();

  return entries;
};

const isJobTitle = (line) => {
  return /(developer|engineer|manager|designer|analyst|intern|consultant|specialist|administrator|lead|officer|assistant|executive|director|coordinator|representative|sales|architect|scientist|accountant|teacher|lecturer|professor|researcher)/i.test(
    line,
  );
};

const isCompanyLine = (line) => {
  return /(ltd\.?|limited|inc\.?|llc|corp\.?|corporation|company|technologies|technology|solutions|software|university|bank|traders|group|industries|foundation|agency|studio|systems)/i.test(
    line,
  );
};

const isGenericExperienceText = (line) => {
  return extractDateRange(line) || isBullet(line) || line.length > 120;
};

const appendExperienceDescription = (current, text) => {
  const cleaned = cleanLine(text);

  if (!cleaned) return;

  current.description = current.description
    ? `${current.description} ${cleaned}`
    : cleaned;
};

const removeDuration = (line) => {
  return line
    .replace(/\s*\(\s*\d+\s*(?:yrs?|years?|months?)\s*\)\s*/i, " ")
    .trim();
};

// ======================================================
// PROJECTS
// ======================================================

const parseProjects = (lines) => {
  const entries = [];

  let current = null;

  const pushCurrent = () => {
    if (!current) return;

    current.name = cleanLine(current.name);

    current.description = cleanLine(current.description);

    if (current.name || current.description) {
      entries.push(current);
    }

    current = null;
  };

  for (const rawLine of lines) {
    const line = cleanLine(rawLine);

    if (!line) continue;

    if (isBullet(line)) {
      if (!current) {
        current = createProject();
        current.name = "Project";
      }

      current.description = appendText(current.description, removeBullet(line));

      continue;
    }

    if (isLikelyProjectHeading(line)) {
      if (current) {
        pushCurrent();
      }

      current = createProject();

      current.name = cleanLine(line);

      continue;
    }

    if (!current) {
      current = createProject();

      current.name = "Project";
    }

    current.description = appendText(current.description, line);
  }

  pushCurrent();

  return entries;
};

const isLikelyProjectHeading = (line) => {
  return (
    line.length >= 2 &&
    line.length <= 100 &&
    !/[.!?]$/.test(line) &&
    !/\d{4}/.test(line) &&
    !isBullet(line) &&
    !looksLikeSentence(line)
  );
};

// ======================================================
// CERTIFICATIONS
// ======================================================

const parseCertifications = (lines) => {
  const result = [];

  for (const rawLine of lines) {
    const line = removeBullet(rawLine);

    if (!line) continue;

    const item = createCertification();

    item.name = cleanLine(
      line.replace(/^(certification|certificate)\s*:\s*/i, ""),
    );

    const year = line.match(/\b((?:19|20)\d{2})\b/);

    if (year) {
      item.year = year[1];
    }

    if (item.name) {
      result.push(item);
    }
  }

  return result;
};

// ======================================================
// LANGUAGES
// ======================================================

const parseLanguages = (lines) => {
  const result = [];

  for (const rawLine of lines) {
    let line = removeBullet(rawLine);

    if (!line) continue;

    if (
      /^(language|languages|language proficiency|language skills)\s*:?\s*$/i.test(
        line,
      )
    ) {
      continue;
    }

    // English - Fluent
    // Bangla – Native
    // English: Fluent
    const dashMatch = line.match(
      /^([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ .'-]{1,40})\s*[-–—:]\s*(.+)$/i,
    );

    if (dashMatch) {
      const language = cleanLine(dashMatch[1]);

      const proficiency = cleanLine(dashMatch[2]);

      if (isKnownLanguage(language)) {
        const item = createLanguage();

        item.language = language;

        item.speaking = proficiency;

        result.push(item);

        continue;
      }
    }

    // CSV / table
    const parts = line
      .split(/[,;|]+/)
      .map(cleanLine)
      .filter(Boolean);

    if (parts.length >= 2 && isKnownLanguage(parts[0])) {
      const item = createLanguage();

      item.language = parts[0];

      item.reading = parts[1] || "";

      item.writing = parts[2] || "";

      item.speaking = parts[3] || "";

      result.push(item);

      continue;
    }

    // Just language name
    if (isKnownLanguage(line)) {
      const item = createLanguage();

      item.language = line;

      result.push(item);
    }
  }

  return uniqueLanguages(result);
};

// Much safer than accepting every alphabetic sentence
// as a language.
const isKnownLanguage = (value) => {
  const cleaned = cleanLine(value).toLowerCase();

  const languages = [
    "english",
    "bangla",
    "bengali",
    "hindi",
    "urdu",
    "arabic",
    "french",
    "german",
    "spanish",
    "italian",
    "portuguese",
    "russian",
    "chinese",
    "mandarin",
    "japanese",
    "korean",
    "turkish",
    "malay",
    "indonesian",
    "nepali",
    "tamil",
    "telugu",
    "punjabi",
    "sinhala",
  ];

  return languages.includes(cleaned);
};

const uniqueLanguages = (items) => {
  const seen = new Set();

  return items.filter((item) => {
    const key = String(item.language || "")
      .toLowerCase()
      .trim();

    if (!key || seen.has(key)) {
      return false;
    }

    seen.add(key);

    return true;
  });
};

// ======================================================
// REFERENCES
// ======================================================

const parseReferences = (lines) => {
  const references = [];

  let current = null;

  const pushCurrent = () => {
    if (!current) return;

    current.name = cleanLine(current.name || "");

    current.organization = cleanLine(current.organization || "");

    current.designation = cleanLine(current.designation || "");

    current.address = cleanLine(current.address || "");

    current.phone = cleanLine(current.phone || "");

    current.email = cleanLine(current.email || "");

    current.relation = cleanLine(current.relation || "");

    if (
      current.name ||
      current.organization ||
      current.designation ||
      current.phone ||
      current.email
    ) {
      references.push(current);
    }

    current = null;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = cleanLine(lines[i]);

    if (!line) continue;

    // Explicit Name:
    if (/^name\s*:/i.test(line)) {
      pushCurrent();

      current = createReference();

      current.name = extractAfterColon(line);

      continue;
    }

    // Detect a new reference by name.
    //
    // Example:
    // Prof. Dr. Utpal Kanti Das
    // Professor & Chair
    // ...
    //
    // Shahinur Alam
    // Professor & Coordinator...
    if (
      current &&
      looksLikeReferenceName(line) &&
      current.name &&
      (current.designation ||
        current.organization ||
        current.phone ||
        current.email)
    ) {
      pushCurrent();

      current = createReference();

      current.name = line;

      continue;
    }

    if (!current) {
      current = createReference();

      current.name = line;

      continue;
    }

    // Organization
    if (/^organization\s*:/i.test(line)) {
      current.organization = extractAfterColon(line);

      continue;
    }

    // Designation
    if (/^designation\s*:/i.test(line)) {
      current.designation = extractAfterColon(line);

      continue;
    }

    // Address
    if (/^address\s*:/i.test(line)) {
      current.address = extractAfterColon(line);

      continue;
    }

    // Phone
    if (/^(phone|mobile|telephone|contact)\s*:/i.test(line)) {
      const value = extractAfterColon(line);

      if (value) {
        current.phone = value;
      }

      continue;
    }

    // Email
    if (/^e-?mail\s*:/i.test(line)) {
      current.email = extractAfterColon(line);

      continue;
    }

    // Relation
    if (/^relation\s*:/i.test(line)) {
      current.relation = extractAfterColon(line);

      continue;
    }

    // Phone without label
    const phone = extractPhones(line)[0];

    if (phone && !current.phone) {
      current.phone = phone;
      continue;
    }

    // Email without label
    const email = extractEmails(line)[0];

    if (email && !current.email) {
      current.email = email;
      continue;
    }

    // Designation
    if (!current.designation && looksLikeDesignation(line)) {
      current.designation = line;
      continue;
    }

    // Institution / organization
    if (!current.organization && isInstitutionLine(line)) {
      current.organization = line;
      continue;
    }

    // Address should be detected conservatively.
    if (!current.address && looksLikeReferenceAddress(line)) {
      current.address = line;
      continue;
    }

    // Organization continuation.
    if (
      current.organization &&
      !looksLikeDesignation(line) &&
      !looksLikeReferenceAddress(line) &&
      !extractEmails(line)[0] &&
      !extractPhones(line)[0]
    ) {
      if (line.length <= 100 && !/[.!?]$/.test(line)) {
        current.organization = `${current.organization} ${line}`;

        continue;
      }
    }
  }

  pushCurrent();

  return references;
};

const looksLikeReferenceName = (line) => {
  const cleaned = cleanLine(line);

  if (cleaned.length < 3 || cleaned.length > 80) {
    return false;
  }

  if (/@|https?:\/\//i.test(cleaned) || /\d{4,}/.test(cleaned)) {
    return false;
  }

  if (
    /^(professor|prof\.?|associate professor|assistant professor|lecturer|chair|coordinator|manager|director|engineer|officer|advisor|consultant|head|lead)\b/i.test(
      cleaned,
    )
  ) {
    return false;
  }

  return /^[A-Za-zÀ-ÿ.'’ -]+$/.test(cleaned);
};

const looksLikeDesignation = (line) => {
  return /(professor|chair|coordinator|manager|director|lecturer|engineer|officer|advisor|consultant|head|lead)/i.test(
    line,
  );
};

const looksLikeReferenceAddress = (line) => {
  return (
    /\b(road|rd|street|st|avenue|ave|sector|block|house|flat|floor|dhaka|bangladesh)\b/i.test(
      line,
    ) || /^\d+[, -]/.test(line)
  );
};

// ======================================================
// SIMPLE LIST
// ======================================================

const parseSimpleList = (lines) => {
  const result = [];

  for (const rawLine of lines) {
    const parts = removeBullet(rawLine)
      .split(/[,;|•]+/)
      .map(cleanLine)
      .filter(Boolean);

    for (const item of parts) {
      if (!isGarbageLine(item)) {
        result.push(item);
      }
    }
  }

  return unique(result);
};

// ======================================================
// DATE / YEAR
// ======================================================

const extractYearRange = (line) => {
  const cleaned = cleanLine(line);

  // 2022(Spring) – Running
  let match = cleaned.match(
    /\b((?:19|20)\d{2})(?:\s*\([^)]*\))?\s*[-–—]\s*(Running|Present|Current)\b/i,
  );

  if (match) {
    return {
      start: match[1],
      end: "Present",
    };
  }

  // 2022(Spring) - 2025
  match = cleaned.match(
    /\b((?:19|20)\d{2})(?:\s*\([^)]*\))?\s*[-–—]\s*((?:19|20)\d{2})\b/,
  );

  if (match) {
    return {
      start: match[1],
      end: match[2],
    };
  }

  // 2022 - Present
  match = cleaned.match(
    /\b((?:19|20)\d{2})\s*[-–—]\s*(Present|Current|Running)\b/i,
  );

  if (match) {
    return {
      start: match[1],
      end: "Present",
    };
  }

  // Single year
  match = cleaned.match(/\b((?:19|20)\d{2})\b/);

  if (match) {
    return {
      start: match[1],
      end: "",
    };
  }

  return null;
};

const extractDateRange = (line) => {
  const month = MONTH_PATTERN;

  let match = line.match(
    new RegExp(
      `(${month}\\.?\\s+\\d{4}|\\d{4})\\s*[-–—]\\s*(${month}\\.?\\s+\\d{4}|\\d{4}|Present|Current)`,
      "i",
    ),
  );

  if (match) {
    return {
      start: cleanLine(match[1]),
      end: cleanLine(match[2]),
    };
  }

  match = line.match(
    /\b((?:19|20)\d{2})\s*[-–—]\s*(Present|Current|Running)\b/i,
  );

  if (match) {
    return {
      start: match[1],
      end: match[2],
    };
  }

  return null;
};

// ======================================================
// BULLETS
// ======================================================

const isBullet = (line) => {
  return /^[-•*▪◦●○◉➢➤►▸]\s*/.test(line.trim());
};

const removeBullet = (line) => {
  return line.replace(/^[-•*▪◦●○◉➢➤►▸]\s*/, "").trim();
};

// ======================================================
// PROJECT / SENTENCE
// ======================================================

const looksLikeSentence = (line) => {
  return /[.!?]$/.test(line) || line.split(/\s+/).length > 14;
};

// ======================================================
// TEXT HELPERS
// ======================================================

const appendText = (existing, value) => {
  const cleaned = cleanLine(value);

  if (!cleaned) {
    return existing || "";
  }

  return existing ? `${existing} ${cleaned}` : cleaned;
};

const appendDescription = (current, text) => {
  const cleaned = cleanLine(text);

  if (!cleaned) return;

  current.description = current.description
    ? `${current.description} ${cleaned}`
    : cleaned;
};

// ======================================================
// CLEANUP
// ======================================================

const cleanupResume = (resume) => {
  resume.skills = unique((resume.skills || []).map(cleanLine).filter(Boolean));

  resume.summary = cleanLine(resume.summary || "");

  resume.education = (resume.education || [])
    .map(finalizeEducation)
    .filter(
      (item) =>
        item.degree || item.institution || item.department || item.result,
    );

  resume.experience = (resume.experience || [])
    .map((item) => ({
      ...item,
      title: cleanLine(item.title || ""),
      company: cleanLine(item.company || ""),
      description: cleanLine(item.description || ""),
    }))
    .filter((item) => item.title || item.company || item.description);

  resume.projects = (resume.projects || [])
    .map((item) => ({
      ...item,
      name: cleanLine(item.name || ""),
      description: cleanLine(item.description || ""),
    }))
    .filter((item) => item.name || item.description);

  resume.languages = uniqueLanguages(resume.languages || []);

  resume.certifications = (resume.certifications || []).filter(
    (item) => item.name,
  );

  resume.achievements = unique(
    (resume.achievements || []).map(cleanLine).filter(Boolean),
  );

  resume.references = (resume.references || []).filter(
    (item) =>
      item.name ||
      item.organization ||
      item.designation ||
      item.phone ||
      item.email,
  );

  return resume;
};

// ======================================================
// EXTRACT AFTER COLON
// ======================================================

const extractAfterColon = (line) => {
  const index = String(line || "").indexOf(":");

  if (index === -1) {
    return "";
  }

  return cleanLine(String(line).slice(index + 1));
};

// ======================================================
// UNIQUE
// ======================================================

const unique = (items) => {
  const seen = new Set();

  return items.filter((item) => {
    const key = String(item).toLowerCase().trim();

    if (!key || seen.has(key)) {
      return false;
    }

    seen.add(key);

    return true;
  });
};

// ======================================================
// REGEX ESCAPE
// ======================================================

const escapeRegex = (value) => {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
};
